"""Add geohash quorum and escalation fields

Revision ID: d5e4694e6dba
Revises: 4bc740cb655c
Create Date: 2026-08-09 13:32:06.911396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e4694e6dba'
down_revision: Union[str, Sequence[str], None] = '4bc740cb655c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvote_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upvote_rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upvote_rate_limits_user_id'), ['user_id'], unique=False)

    op.create_table('quorum_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quorum_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quorum_votes_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quorum_votes_user_id'), ['user_id'], unique=False)

    op.create_table('upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upvotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upvotes_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upvotes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geohash', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('ward', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('fuzz_location', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_fuzzed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_shielded', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('upvotes_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('resolution_proof', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confirmations_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('disputes_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quorum_expires_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_issues_geohash'), ['geohash'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_ward'), ['ward'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_ward'))
        batch_op.drop_index(batch_op.f('ix_issues_geohash'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
        batch_op.drop_column('quorum_expires_at')
        batch_op.drop_column('disputes_count')
        batch_op.drop_column('confirmations_count')
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolution_proof')
        batch_op.drop_column('upvotes_count')
        batch_op.drop_column('escalated_at')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('is_shielded')
        batch_op.drop_column('is_fuzzed')
        batch_op.drop_column('fuzz_location')
        batch_op.drop_column('ward')
        batch_op.drop_column('geohash')

    with op.batch_alter_table('upvotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upvotes_user_id'))
        batch_op.drop_index(batch_op.f('ix_upvotes_issue_id'))

    op.drop_table('upvotes')
    with op.batch_alter_table('quorum_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quorum_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_quorum_votes_issue_id'))

    op.drop_table('quorum_votes')
    with op.batch_alter_table('upvote_rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upvote_rate_limits_user_id'))

    op.drop_table('upvote_rate_limits')
    # ### end Alembic commands ###
